on:
  pull_request_review:
    types: [submitted, edited]
  workflow_run:
    types: [completed]
    workflows: ["conan"]

name: "auto merge"

jobs:
  automerge:
    name: Auto Merge Pull Requests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: debug
        run: |
          pip install PyGithub
          python auto-merge.py
